server {
	listen 127.0.0.1:8081;
	server_name site-one;

	error_page 404 ./www/errors/404.html;

	location / {
		root ./www;
		index index.html;
		allowed_methods GET;
		autoindex off;
	}
}

server {
	listen 127.0.0.1:8082;
	server_name site-two;

	error_page 404 ./www/errors/404.html;

	location / {
		root ./cgi-bin;
		index hello.py;
		allowed_methods GET;
		autoindex off;
	}
}
