server {
	listen 127.0.0.1:3000;
	server_name localhost;

	client_max_body_size 10000;

	error_page 404 ./errors/404.html;
	error_page 500 ./errors/500.html;

	location / {
		root ./www;
		index index.html;

		allowed_methods GET POST DELETE;

		autoindex off;

		upload_dir on ./uploads;
		cgi .py /usr/bin/python3;
	}

	location /uploads {
		root ./uploads;

		allowed_methods GET POST DELETE;

		upload_dir on ./uploads;
		autoindex on;
	}

	location /redirect {
		return 301 https://example.com;
	}

	location /cgi-bin {
		root ./cgi-bin;

		allowed_methods GET POST;
		cgi .py /usr/bin/python3;
	}
}