server {
    listen 0.0.0.0:3000;
    server_name localhost;
    client_max_body_size 100;
    
    location / {
        root YoupiBanane;
        allowed_methods GET;
    }
    
    location /post_body {
        root YoupiBanane;
        allowed_methods POST;
    }
    
    location /directory/ {
        root YoupiBanane;
        allowed_methods GET;
        index YoupiBanane/index.html;
    }
    
    location /youpi.bla {
        root YoupiBanane;
        allowed_methods POST;
        cgi .bla YoupiBanane/cgi_tester;
    }
}